config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  root 'categories#index'
  resources :categories do
    resources :tracks
  end

  resources :tracks do
    resources :lessons
  end

  resources :lessons do
    resources :resources
    resources :assessments
  end

  resources :assessments do
    resources :questions
  end

  resources :users do 
    resources :messages
  end
  resources :questions do 
    resources :answers
  end 

  resources :students_tracks

  get '/shuffle' => 'resources#shuffle', as: :shuffle

  get '/factoids' => 'factoids#show', as: :random_fact

  post 'resources/:id/complete' => 'resources#complete', as: :complete_element

end

app/models/track.rb
# == Schema Information
#
# Table name: tracks
#
#  id          :integer          not null, primary key
#  privacy     :boolean
#  teacher_id  :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  category_id :integer
#  name        :string
#  description :string
#  image_url   :string
#

class Track < ActiveRecord::Base
  has_many :lessons
  belongs_to :teacher
  belongs_to :category
  has_many :students_tracks
  has_many :students, through: :students_tracks

  validates :image_url, allow_blank: true, format: { with: %r{.(gif|jpg|png)\Z}i, message: 'must be a URL for GIF, JPG or PNG image.' }



  def completion
    if self.lessons.all? {|lesson| lesson.completed}
      self.update(completed: true)
    end
  end

  def is_user_a_student_of_track(user)
    if user.student != nil
      student = StudentsTrack.find_by(student_id: user.student.id, track_id: self.id)
    else
      student = nil
    end

    if student != nil
      return true
    else
      return false
    end

  end

  def is_user_a_teacher_of_track(user)
    self.teacher.user_id == user.id
  end


  #method to return an array of all the students in a track
  def students_in_the_track
    self.students
  end


  # method to return an array of all the students in a class ranked by points
  def students_in_the_track_ranked(track)
    self.students.sort_by { |student| student.user.points}
  end


end

app/controllers/tracks_controller.rb
# == Schema Information
#
# Table name: tracks
#
#  id          :integer          not null, primary key
#  privacy     :boolean
#  teacher_id  :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  category_id :integer
#  name        :string
#  description :string
#  image_url   :string
#

class TracksController < ApplicationController


  before_action :authorized_to_interact, only: [:edit]

  def show
    @track = Track.find(params[:id])
    @lessons = @track.lessons.sort_by {|lesson| lesson.order_id}

    @is_enrolled = @track.is_user_a_student_of_track(current_user)
    @is_teacher = @track.is_user_a_teacher_of_track(current_user)
    @student = Student.find_by(user_id: current_user.id)

    if @student != nil
      @completion= @student.percent_complete(@track)
    else
      @completion = 0
    end
    @teacher= Teacher.find(@track.teacher_id)
  end

  def new
    @cat = Category.find(params[:category_id])
    @track = @cat.tracks.new()
  end

  def create

    if current_user.teacher == nil
        Teacher.create(user_id: current_user.id)
    end
    @track = Track.create(track_params)
    @track.teacher_id = current_user.teacher.id

    if @track.valid?
      @track.save
      @lesson = @track.lessons.build()
      @teacher = current_user.teacher
      redirect_to new_track_lesson_path(@track)
    else
      render 'new'
    end
  end

  def enroll
    redirect_to track_path(@track)
  end

  private

  def track_params
    params.require(:track).permit(:name, :description, :category_id, :image_url)
  end

  def authorized_to_edit
    @track=Track.find(params[:id])
    @teacher= Teacher.find(@track.teacher_id)
    if session[:user_id] != @teacher.user_id
        redirect_to root_path, notice: "You must be a Track's teacher in order to edit its contents"
    end
  end

end

app/helpers/tracks_helper.rb
# == Schema Information
#
# Table name: tracks
#
#  id          :integer          not null, primary key
#  privacy     :boolean
#  teacher_id  :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  category_id :integer
#  name        :string
#  description :string
#  image_url   :string
#

module TracksHelper
end

app/views/tracks/_link_to_new_lesson.html.erb
<p><% if @teacher.id == current_user.teacher.id%>
  <%= link_to 'Add a Lesson', new_track_lesson_path(@track) %>
  <% end %>
</p>

app/views/tracks/_notenrolled.html.erb
<div class="alert alert-info alert-dismissible" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  <strong>Welcome!</strong> Enroll to see details and get started!
</div>

<ul>
  <% @lessons.each do |lesson| %>
    <li><%= lesson.title %> - <%= lesson.duration %></li>
  <% end %>
</ul>

<%= form_tag students_tracks_path, method: :post do %>
<%= hidden_field_tag(:track_id, @track.id) %>
  <%= submit_tag "Enroll" %>
<% end %>

app/views/tracks/_showenrolledstudent.html.erb
<h3>Progress Bar:</h3>
<div class="progress">
  <div class="progress-bar" role="progressbar" aria-valuenow="<%= @completion %>" aria-valuemin="0" aria-valuemax="100" style="width: <%= @completion %>%;">
    <%=  @completion %>%
  </div>
</div>
<p><%= @completion %>% completed</p>

<% if @student.enrollment_date(@track) < current_user.current_sign_in_at + 60*60 %> 
  <div class="alert alert-success alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <strong>You are enrolled!</strong> Click on the lessons below and start learning!
  </div>
<% end %>

<ul>
  <% @lessons.each do |lesson| %>
    <li><%= link_to lesson.title, lesson_path(lesson) %> - <%= lesson.duration %></li>
  <% end %>
</ul>

app/views/tracks/_teachershow.html.erb
<ul>
  <% @lessons.each do |lesson| %>
  <li><%= link_to lesson.title, lesson_path(lesson) %> - <%= lesson.duration %></li>
  <% end %>
</ul>

<p><%= link_to "Add a Lesson", new_track_lesson_path(@track) %></p>

app/views/tracks/create.js.erb
$('#lesson_form').html("<%= j (render 'new_lesson') %>")

app/views/tracks/new.html.erb
<br>
<% if params[:category_id] %>
  <h2>Build a new track in <%= Category.find(params[:category_id]).title %></h2>
<% else %>
  <h2>Build a new track</h2>
<% end %>

<% if @track.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <ul>
      <% @track.errors.full_messages.each do |error| %>
        <li><%= error %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="form-style-6" id="new_lesson_form">

  <%= form_for @track, :html => {:class => "form-creation"} do |f|%>
  <%= f.text_field :name, placeholder: "Name" %>
  <%= f.text_field :description, placeholder: "Description", style: "height: 125px;"%>
  <%= f.text_field :image_url, placeholder: "Image URL" %>
  <%= f.hidden_field :category_id %>

  <%= f.submit  %>
  <% end %>

</div>

app/views/tracks/show.html.erb
<div class="page-header">
  <h1>
  <%= @track.name %><br>
  <small> <%= @track.description %></small>
  </h1>
</div>


<% if @is_enrolled %>
  <%= render "showenrolledstudent" %>
<% elsif @is_enrolled == false && @is_teacher == false %>
  <%= render "notenrolled" %>
<% end %>

<% if @is_teacher %>
  <%= render "teachershow" %>
<% end %>

<div class="create-new-track">
  <br>
  <%= link_to(category_path(@track.category)) do %>
  <p><span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span>
    Return to <%= @track.category.title %> Tracks</p>
    <% end %>
</div>