config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  root 'categories#index'
  resources :categories do
    resources :tracks
  end

  resources :tracks do
    resources :lessons
  end

  resources :lessons do
    resources :resources
    resources :assessments
  end

  resources :assessments do
    resources :questions
  end

  resources :users do 
    resources :messages
  end
  resources :questions do 
    resources :answers
  end 

  resources :students_tracks

  get '/shuffle' => 'resources#shuffle', as: :shuffle

  get '/factoids' => 'factoids#show', as: :random_fact

  post 'resources/:id/complete' => 'resources#complete', as: :complete_element

end

app/models/lesson.rb
# == Schema Information
#
# Table name: lessons
#
#  id         :integer          not null, primary key
#  title      :string
#  track_id   :integer
#  duration   :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  order_id   :integer
#

class Lesson < ActiveRecord::Base
  has_many :resources
  has_many :assessments
  belongs_to :track
  has_many :students_lessons
  has_many :students, through: :students_lessons

end

app/controllers/lessons_controller.rb
# == Schema Information
#
# Table name: lessons
#
#  id         :integer          not null, primary key
#  title      :string
#  track_id   :integer
#  duration   :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  order_id   :integer
#

class LessonsController < ApplicationController
  before_action :authorized_to_interact, only: [:edit]

  def show
    @lesson = Lesson.find(params[:id])
    @all_resources = @lesson.resources
    @assessments = @lesson.assessments
    @student = Student.find_by(user_id: current_user.id)

    @answer = Answer.new
    @teacher = Teacher.find_by(user_id: current_user.id)

    unless @student.nil?
      joins = @all_resources.select do |r|
        StudentsResource.find_by(resource_id: r.id, student_id: @student.id)
      end

      @completed_joins= joins.find_all{|r| r.students_resources[0].completed}
      @complete_resources= @completed_joins.map {|j| j}
      @incomplete_joins= joins.find_all{|r| r.students_resources[0].completed == false}
      @incomplete_resources= @incomplete_joins.map {|j| j}
      @all_student_resources = @complete_resources + @incomplete_resources
    end 
  end

  def new
    @track= Track.find(params[:track_id])
    @lesson = @track.lessons.build()
  end

  def create

    @lesson = Lesson.new(title: params["title"], track_id: params["track_id"], duration: params["duration"])
    @track = @lesson.track
    @lesson.order_id = @track.lessons.length
    @lesson.save
    @teacher = @track.teacher
    #redirect_to lesson_path(@lesson)

    @return = { :error => false, :response => "Added", :partial => render_to_string(:partial => "link_to_new_lesson", :object => @teacher) }
    render json: {lesson: @lesson, return: @return}
  end

  private
  def lesson_params
    params.require(:lesson).permit!
  end

  def authorized_to_edit
    @lesson=Lesson.find(params[:id])
    @teacher= Teacher.find(@lesson.track.teacher_id)
    if session[:user_id] != @teacher.user_id
        redirect_to root_path, notice: "You must be a Track's teacher in order to edit its contents"
    end
  end
end

app/helpers/lessons_helper.rb
# == Schema Information
#
# Table name: lessons
#
#  id         :integer          not null, primary key
#  title      :string
#  track_id   :integer
#  duration   :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  order_id   :integer
#

module LessonsHelper
end

app/views/lessons/_link_to_new_lesson.html.erb
<div id="new_alert" class="alert alert-info alert-dismissible">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
</div>

<!-- <%= form_for @lesson, remote: true do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :duration %>
  <%= f.text_field :duration %>
  <%= f.hidden_field :track_id %>
  <%= f.submit %>
  <% end %> -->

<div id="lesson_form"></div>
<p><% if @teacher.id == current_user.teacher.id%>
  <%= link_to 'Add More Lessons', new_track_lesson_path(@track) %><br>
  <%= link_to 'Return To Track', track_path(@track) %>
  <% end %>
</p>

app/views/lessons/new.html.erb
<br>
<h2>Create a new lesson for <strong><%= @track.name %></strong> </h2>

<div class="form-style-6">
  <%= form_for @lesson, remote: true do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>
    <%= f.label :duration %>
    <%= f.text_field :duration %>
    <%= f.hidden_field :track_id %>
    <%= f.submit %>
  <% end %>
</div>

<div id="lesson_form"></div>

app/views/lessons/show.html.erb
<br>
<h1><%= @lesson.title %> in the <%= link_to @lesson.track.name, track_path(@lesson.track) %> Track</h1>

<h2>Lesson Content
  <% if current_user.teacher == @lesson.track.teacher %>

    <%= link_to "Add Resource", new_lesson_resource_path(@lesson), class: "btn btn-default btn-lg" %>

    <%= link_to "Create Assessment", new_lesson_assessment_path(@lesson), class: "btn btn-default btn-lg"%>

  <% end %>
</h2>

 <div class='tabs tabs_active'>
    <ul class='horizontal list-group'>

    <% if current_user.teacher == @lesson.track.teacher %>

      <li class="list-group-item"><a href="#tab-1">Resources</a></li>
      <li class="list-group-item"><a href="#tab-2">Assessments</a></li>

    <% elsif !@assessments.nil? && !@assessments.last.nil? && !@incomplete_resources.nil? %>
      <li class="list-group-item"><span class="badge"><%= @incomplete_resources.length %></span><a href="#tab-1">Resources</a></li>

     <li class="list-group-item"><span class="badge"><%= @assessments.last.questions.length - @student.answers.find_all{|a| a.assessment == @assessments.last}.length %></span><a href="#tab-2">Assessments</a></li>

    <% end %>
    </ul>


<!-- Pages rendered by tab  -->
<% if @lesson.track.teacher.user_id == current_user.id %>  

  <div id='tab-1'><%= render "resources/showteacher" %></div>
  <div id='tab-2'><%= render partial: "resources/assessmentteacher", locals: {assessments: @assessments, lesson: @lesson, answer: @answer, student: @student} %></div>
</div>

<% else %>  

  <div id='tab-1'><%= render "resources/showstudent" %></div>
  <div id='tab-2'><%= render partial: "resources/assessmentstudent", locals: {assessments: @assessments, answer: @answer, student: @student} %></div>
</div>

<hr>

<div class="completed-resources">
</div>

<% end %>