config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  root 'categories#index'
  resources :categories do
    resources :tracks
  end

  resources :tracks do
    resources :lessons
  end

  resources :lessons do
    resources :resources
    resources :assessments
  end

  resources :assessments do
    resources :questions
  end

  resources :users do 
    resources :messages
  end
  resources :questions do 
    resources :answers
  end 

  resources :students_tracks

  get '/shuffle' => 'resources#shuffle', as: :shuffle

  get '/factoids' => 'factoids#show', as: :random_fact

  post 'resources/:id/complete' => 'resources#complete', as: :complete_element

end

app/views/resources/_assessmentstudent.html.erb
<% Assessment.all_questions(@lesson).flatten.each_with_index do |question, index| %>
  <% if student.find_answer(question).empty? %>
    <div class="panel panel-primary">
  <% elsif student.find_answer(question)[0].total_point_value == 0 || !student.find_answer(question)[0].correct %>
    <div class="panel panel-danger">
  <% elsif student.find_answer(question)[0].total_point_value != nil && student.find_answer(question)[0].total_point_value > 0 || student.find_answer(question)[0].correct %>
    <div class="panel panel-success">
  <% else  %>
    <div class="panel panel-default">
  <% end %>

      <div class="panel-heading">
        <h3 class="panel-title"><%= index + 1 %>. <%= question.content %></h3>
      </div>
      <div class="panel-body">

      <div class="answer-<%= question.id %>">
      
      <% if student.find_answer(question).empty? %> <!-- checks if student already answered question -->
        <%= form_for question.answers.build(), {url: question_answers_path(question)} do |f| %>
          <%= f.text_field  :content %>
          <%= f.hidden_field :student_id, {:value => student.id } %>
          <%= f.hidden_field :assessment_id, {:value => question.assessment.id} %>
          <%= f.hidden_field :question_id, { :value => question.id} %>
          <%= f.submit "Answer", id: "answer" %><br>
        <% end %>

      <% elsif student.find_answer(question)[0].correct %>
          <%= student.find_answer(question)[0].content %>
          <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
      <% elsif !student.find_answer(question)[0].correct %>
          <%= student.find_answer(question)[0].content %>
          <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
      <% else %>
          <%= student.find_answer(question)[0].content %><br>
          <%= link_to "Edit Answer", edit_question_answer_path(question, student.find_answer(question)[0]), class: "edit-answer #{student.find_answer(question)[0].id}", remote: true %>
      <% end %>

      </div>
      </div>
    </div>

<% end %>

app/views/resources/_assessmentteacher.html.erb
<% Assessment.all_questions(lesson).flatten.each_with_index do |question, index| %>

  <div class="panel panel-default">
    <div class="panel-heading">
      Question <%= index + 1 %>
    </div>

    <div class="panel-body">
      <p><%= question.content %><br>
        <% unless question.correct_answer === '' || nil %>
          Answer: <strong><%= question.correct_answer %></strong>
        <% end %>
      </p>
        <button type="button" class="btn btn-primary btn-sml">
          See Student Answers
        </button>
    </div>

    <table class="table" id="answers <%= question.id %>">
      <tr>
        <th><strong>User</strong></th>
        <th><strong>Answer</strong></th>
        <th><strong>Grade</strong></th>

      </tr>

    <% question.answers.each do |answer| %>
      <tr>

      <td><%= answer.student.user.email %></td>
      <td><%= answer.content %></td>
      <td>
      <% if question.correct_answer == "" || nil %>
        <%= form_for answer, url: question_answer_path(question, answer), html: {method: "patch"}, remote: true do |f| %>
          <%= f.label :total_point_value, '0', class: "radio-inline" %>
          <%= f.radio_button :total_point_value, '0'%>
          <%= f.label :total_point_value, '1', class: "radio-inline" %>
          <%= f.radio_button :total_point_value, '1'%>
          <%= f.label :total_point_value, '2', class: "radio-inline" %>
          <%= f.radio_button :total_point_value, '2'%>
          <% if answer.total_point_value.nil? %>
            <%= f.submit "Save Grade", class: "btn btn-success btn-xs" %>
          <% else %>
             <%= f.submit "Saved!", class: "btn btn-success btn-xs" %>
          <% end %>
          <% end %>
       <% else %>
          <% if answer.correct %>
            <p>2 points</p>
          <% else %>
            <p>0 points</p>
          <% end %>
      </td>
      <% end %>

    <% end %>
    </table>
  </div>

<% end %>

app/views/resources/_show_completed.html.erb
 <!--=== Resources section Starts ===-->
  <section id="section-feature" class="feature-wrap">
    <div class="container features center">
      <div class="row">
        <div class="col-lg-12">
            <!--Resource container Starts -->
            <% if @complete_resources != nil %>
            <ul id="card-ul" class="features-hold baraja-container">


            <% @complete_resources.each do |obj| %>

              <% if obj.class == Resource %>

                <!-- Single Resource Starts -->
                <li class="single-feature" id="<%= obj.id %>" title="Card style">

                <% if obj.type_of == "Video" %>
                  <%= image_tag "http://img.youtube.com/vi/#{obj.video_id}/hqdefault.jpg", :class => "feature-image" %>
                <% elsif obj.type_of == "Image" %>
                  <%= image_tag obj.content, :class => "feature-image" %>
                <% elsif obj.type_of == "Reading" %>
                  <%= image_tag "http://icons.iconarchive.com/icons/martz90/circle/512/books-icon.png", :class => "feature-image" %>
                <% elsif obj.type_of == "Audio" %>
                  <%= image_tag "http://aldemedianoche.com.ar/wp-content/uploads/2015/01/audio.png", :class => "feature-image" %>
                <% elsif obj.type_of == "Audio" %>
                  <%= image_tag "logo", :class => "feature-image" %>
                <% end %><!-- Resource Icon -->

                  <h4 class="feature-title color-scheme"><%= obj.title %></h4>

                  <p class="feature-text">
                  <%= obj.description %>
                  </p>

                <% if obj.type_of == "Video" %>
                  <%= link_to "Open", obj.content, id: "popup-youtube", class: "btn btn-success btn-sm" %>
                <% elsif obj.type_of == "Image" %>
                  <%= link_to "Open", obj.content, id: "image-popup-vertical-fit", class: "btn btn-success btn-sm" %>
                <% elsif obj.type_of == "Reading" %>
                  <%= link_to "Open", obj.content, class: "btn btn-success btn-sm"%>
                <% elsif obj.type_of == "Audio" %>
                  <%= link_to "Open", obj.content, class: "btn btn-success btn-sm"  %>
                <% elsif obj.type_of == "Other" %>
                  <%= link_to "Open", obj.content, class: "btn btn-success btn-sm"  %>
                <% end %>

                  <%= link_to "Mark as Complete", "#", class: "btn btn-info btn-sm" %>

                </li>
                <!-- Single Resource Ends -->
                <% end %>
            <% end %>
          </ul>
          <% end %>
            <!--Resource container Ends -->

            <!-- Resources Controls Starts -->
            <div class="features-control relative">
              <button class="control-icon fancy-button button-line no-text btn-col bell" id="feature-prev" title="Previous" >
                <span class="glyphicon glyphicon-triangle-left" aria-hidden="true"></span>
              </button>
              <button class="control-icon fancy-button button-line no-text btn-col zoom" id="feature-expand" title="Expand" >
                <span class="glyphicon glyphicon-resize-full" aria-hidden="true"></span>
              </button>
              <button class="control-icon fancy-button button-line no-text btn-col zoom" id="feature-close" title="Collapse" >
                <span class="glyphicon glyphicon-resize-small" aria-hidden="true"></span>
              </button>
              <button class="control-icon fancy-button button-line no-text btn-col bell" id="feature-next" title="Next" >
                <span class="glyphicon glyphicon-triangle-right" aria-hidden="true"></span>
              </button>
            </div>
            <!-- Resources Controls Ends -->
        </div>
      </div>
    </div>
  </section>

app/views/resources/_showstudent.html.erb
 <!--=== Resources section Starts ===-->
  <section id="section-feature" class="feature-wrap">
    <div class="container features center">
      <div class="row">
        <div class="col-lg-12">
            <!--Resource container Starts -->
            <% if @all_student_resources != nil %>
            <ul id="card-ul" class="features-hold baraja-container">


            <% @all_student_resources.each do |obj| %>

              <% if obj.class == Resource %>

                <!-- Single Resource Starts -->
                <li class="single-feature" id="<%= obj.id %>" title="Card style">

                <% if obj.type_of == "Video" %>
                  <%= image_tag "http://img.youtube.com/vi/#{obj.video_id}/hqdefault.jpg", :class => "feature-image" %>
                <% elsif obj.type_of == "Image" %>
                  <%= image_tag obj.content, :class => "feature-image" %>
                <% elsif obj.type_of == "Reading" %>
                  <%= image_tag "http://icons.iconarchive.com/icons/martz90/circle/512/books-icon.png", :class => "feature-image" %>
                <% elsif obj.type_of == "Audio" %>
                  <%= image_tag "http://aldemedianoche.com.ar/wp-content/uploads/2015/01/audio.png", :class => "feature-image" %>
                <% elsif obj.type_of == "Audio" %>
                  <%= image_tag "logo", :class => "feature-image" %>
                <% elsif obj.type_of == "Other" %>
                  <% if obj.lesson.track.category.title == "Health" %>
                    <%= image_tag "Health", :class => "feature-image" %>
                  <% elsif obj.lesson.track.category.title == "Art" %>
                    <%= image_tag "Art", :class => "feature-image" %>
                  <% elsif obj.lesson.track.category.title == "Music" %>
                    <%= image_tag "Music", :class => "feature-image" %>
                  <% elsif obj.lesson.track.category.title == "History" %>
                    <%= image_tag "History", :class => "feature-image" %>
                  <% elsif obj.lesson.track.category.title == "STEM" %>
                    <%= image_tag "STEM", :class => "feature-image" %>
                  <% elsif obj.lesson.track.category.title == "Language" %>
                    <%= image_tag "Language", :class => "feature-image" %> 
                  <% end %>
                <% end %><!-- Resource Icon -->

                  <h4 class="feature-title color-scheme"><%= obj.title %></h4>

                  <p class="feature-text">
                  <%= obj.description %>
                  </p>

                <% if obj.type_of == "Video" %>
                  <%= link_to "Open", obj.content, id: "popup-youtube", class: "btn btn-success btn-sm" %>
                <% elsif obj.type_of == "Image" %>
                  <%= link_to "Open", obj.content, id: "image-popup-vertical-fit", class: "btn btn-success btn-sm" %>
                <% elsif obj.type_of == "Reading" %>
                  <%= link_to "Open", obj.content, class: "btn btn-success btn-sm", target: "_blank" %>
                <% elsif obj.type_of == "Audio" %>
                  <%= link_to "Open", obj.content, target: "_blank", class: "btn btn-success btn-sm"  %>
                <% elsif obj.type_of == "Other" %>
                  <%= link_to "Open", obj.content, target: "_blank", class: "btn btn-success btn-sm"  %>
                <% end %>

                  <% if obj.students_resources.where(student_id: current_user.student.id)[0].completed == false %>
                    <%= link_to "Mark as Complete", complete_element_path(obj), method: :post, class: "btn btn-info btn-sm", id: obj.id, remote: true %>
                  <% else %>
                    <%= link_to "Completed!", "#", class: "btn btn-default btn-sm"%>
                  <% end %>

                </li>
                <!-- Single Resource Ends -->
                <% end %>
            <% end %>
          </ul>
          <% end %>
            <!--Resource container Ends -->

            <!-- Resources Controls Starts -->
            <div class="features-control relative">
              <button class="control-icon fancy-button button-line no-text btn-col bell" id="feature-prev" title="Previous" >
                <span class="glyphicon glyphicon-triangle-left" aria-hidden="true"></span>
              </button>
              <button class="control-icon fancy-button button-line no-text btn-col zoom" id="feature-expand" title="Expand" >
                <span class="glyphicon glyphicon-resize-full" aria-hidden="true"></span>
              </button>
              <button class="control-icon fancy-button button-line no-text btn-col zoom" id="feature-close" title="Collapse" >
                <span class="glyphicon glyphicon-resize-small" aria-hidden="true"></span>
              </button>
              <button class="control-icon fancy-button button-line no-text btn-col bell" id="feature-next" title="Next" >
                <span class="glyphicon glyphicon-triangle-right" aria-hidden="true"></span>
              </button>
            </div>
            <!-- Resources Controls Ends -->
        </div>
      </div>
    </div>
  </section>

app/views/resources/_showteacher.html.erb
 <!--=== Resources section Starts ===-->
  <section id="section-feature" class="feature-wrap">
    <div class="container features center">
      <div class="row">
        <div class="col-lg-12">
            <!--Resource container Starts -->
            <% if @all_resources != nil %>
            <ul id="card-ul" class="features-hold baraja-container">


            <% @all_resources.each do |obj| %>

              <% if obj.class == Resource %>

                <!-- Single Resource Starts -->
                <li class="single-feature" id="<%= obj.id %>" title="Card style">

                <% if obj.type_of == "Video" %>
                  <%= image_tag "http://img.youtube.com/vi/#{obj.video_id}/hqdefault.jpg", :class => "feature-image" %>
                <% elsif obj.type_of == "Image" %>
                  <%= image_tag obj.content, :class => "feature-image" %>
                <% elsif obj.type_of == "Reading" %>
                  <%= image_tag "http://icons.iconarchive.com/icons/martz90/circle/512/books-icon.png", :class => "feature-image" %>
                <% elsif obj.type_of == "Audio" %>
                  <%= image_tag "http://aldemedianoche.com.ar/wp-content/uploads/2015/01/audio.png", :class => "feature-image" %>
                <% elsif obj.type_of == "Audio" %>
                  <%= image_tag "logo", :class => "feature-image" %>
                <% elsif obj.type_of == "Other" %>
                  <% if obj.lesson.track.category.title == "Health" %>
                    <%= image_tag "health", :class => "feature-image" %>
                  <% elsif obj.lesson.track.category.title == "Art" %>
                    <%= image_tag "art", :class => "feature-image" %>
                  <% elsif obj.lesson.track.category.title == "Music" %>
                    <%= image_tag "music", :class => "feature-image" %>
                  <% elsif obj.lesson.track.category.title == "History" %>
                    <%= image_tag "history", :class => "feature-image" %>
                  <% elsif obj.lesson.track.category.title == "STEM" %>
                    <%= image_tag "stem", :class => "feature-image" %>
                  <% elsif obj.lesson.track.category.title == "Language" %>
                    <%= image_tag "language", :class => "feature-image" %>
                  <% end %>
                <% end %><!-- Resource Icon -->

                  <h4 class="feature-title color-scheme"><%= obj.title %></h4>

                  <p class="feature-text">
                  <%= obj.description %>
                  </p>

                <% if obj.type_of == "Video" %>
                  <%= link_to "Open", obj.content, id: "popup-youtube", class: "btn btn-success btn-sm" %>
                <% elsif obj.type_of == "Image" %>
                  <%= link_to "Open", obj.content, id: "image-popup-vertical-fit", class: "btn btn-success btn-sm" %>
                <% elsif obj.type_of == "Reading" %>
                  <%= link_to "Open", obj.content, class: "btn btn-success btn-sm", target: "_blank" %>
                <% elsif obj.type_of == "Audio" %>
                  <%= link_to "Open", obj.content, target: "_blank", class: "btn btn-success btn-sm"  %>
                <% elsif obj.type_of == "Other" %>
                  <%= link_to "Open", obj.content, target: "_blank", class: "btn btn-success btn-sm"  %>
                <% end %>

                </li>
                <!-- Single Resource Ends -->
                <% end %>
            <% end %>
          </ul>
          <% end %>
            <!--Resource container Ends -->

            <!-- Resources Controls Starts -->
            <div class="btn-group btn-group-lg" role="group">
              <div class="btn-group" role="group">
              <button class="control-icon fancy-button button-line no-text btn-col bell" id="feature-prev" title="Previous" >
                <span class="glyphicon glyphicon-triangle-left" aria-hidden="true"></span>
              </button>
              </div>
              <div class="btn-group" role="group">
              <button class="control-icon fancy-button button-line no-text btn-col zoom" id="feature-expand" title="Expand" >
                <span class="glyphicon glyphicon-resize-full" aria-hidden="true"></span>
              </button>
              </div>
              <div class="btn-group" role="group">
              <button class="control-icon fancy-button button-line no-text btn-col zoom" id="feature-close" title="Collapse" >
                <span class="glyphicon glyphicon-resize-small" aria-hidden="true"></span>
              </button>
              </div>
              <div class="btn-group" role="group">
              <button class="control-icon fancy-button button-line no-text btn-col bell" id="feature-next" title="Next" >
                <span class="glyphicon glyphicon-triangle-right" aria-hidden="true"></span>
              </button>
              </div>
            </div>
            <!-- Resources Controls Ends -->
        </div>
      </div>
    </div>
  </section>

app/views/resources/complete.js.erb
$('a#<%= @resource.id %>.btn').text("Completed!");
$('#feature-close').click();
$('#feature-next').click();
swal("Great job!", "You earned 5 points!", "success")

app/views/resources/new.html.erb
<br>
<h2>Add a new resource for <strong><%= @lesson.title %></strong> </h2>
<br>

<div class="form-style-6">
  <%= form_for @resource, url: lesson_resources_path(@lesson) do |f| %>
  <%= f.label :type_of, "Type" %>
  <%= f.select :type_of, ["Reading", "Image", "Video","Audio", "Other"] %>

  <%= f.label :title %>
  <%= f.text_field :title%>

  <%= f.label :description %>
  <%= f.text_field :description %>

  <%= f.label :content, 'URL' %>
  <%= f.text_field :content %>
  <%= f.submit %>
  <% end %>
</div>

app/views/resources/shuffle.html.erb
 <%= image_tag "shuffle", :style => "padding-left: 100px"%>
 <!--=== Resources section Starts ===-->
  <section id="section-feature-shuffle" class="feature-wrap">
    <div class="container features center">
      <div class="row">
        <div class="col-lg-12">
            <!--Resource container Starts -->
            <% if @resources != nil %>
            <ul id="card-ul-shuffle" class="features-hold baraja-container">


            <% @resources.shuffle.each do |obj| %>

              <% if obj.class == Resource %>

                <!-- Single Resource Starts -->
                <li class="single-feature" id="<%= obj.id %>" title="Card style">

                <% if obj.type_of == "Video" %>
                  <%= image_tag "http://img.youtube.com/vi/#{obj.video_id}/hqdefault.jpg", :class => "feature-image" %>
                <% elsif obj.type_of == "Image" %>
                  <%= image_tag obj.content, :class => "feature-image" %>
                <% elsif obj.type_of == "Reading" %>
                  <%= image_tag "http://icons.iconarchive.com/icons/martz90/circle/512/books-icon.png", :class => "feature-image" %>
                <% elsif obj.type_of == "Audio" %>
                  <%= image_tag "http://aldemedianoche.com.ar/wp-content/uploads/2015/01/audio.png", :class => "feature-image" %>
                <% elsif obj.type_of == "Audio" %>
                  <%= image_tag "logo", :class => "feature-image" %>
                <% elsif obj.type_of == "Other" && !obj.lesson.track.nil? %>
                  <% if obj.lesson.track.category.title == "Health" %>
                    <%= image_tag "health", :class => "feature-image" %>
                  <% elsif obj.lesson.track.category.title == "Art" %>
                    <%= image_tag "art", :class => "feature-image" %>
                  <% elsif obj.lesson.track.category.title == "Music" %>
                    <%= image_tag "music", :class => "feature-image" %>
                  <% elsif obj.lesson.track.category.title == "History" %>
                    <%= image_tag "history", :class => "feature-image" %>
                  <% elsif obj.lesson.track.category.title == "STEM" %>
                    <%= image_tag "stem", :class => "feature-image" %>
                  <% elsif obj.lesson.track.category.title == "Language" %>
                    <%= image_tag "language", :class => "feature-image" %>
                  <% end %>
                <% end %><!-- Resource Icon -->

                  <h4 class="feature-title color-scheme"><%= obj.title %></h4>

                  <p class="feature-text">
                  <%= obj.description %>
                  </p>

                <% if obj.type_of == "Video" %>
                  <%= link_to "Open", obj.content, id: "popup-youtube", class: "btn btn-success btn-sm" %>
                <% elsif obj.type_of == "Image" %>
                  <%= link_to "Open", obj.content, id: "image-popup-vertical-fit", class: "btn btn-success btn-sm" %>
                <% elsif obj.type_of == "Reading" %>
                  <%= link_to "Open", obj.content, class: "btn btn-success btn-sm", target: "_blank" %>
                <% elsif obj.type_of == "Audio" %>
                  <%= link_to "Open", obj.content, target: "_blank", class: "btn btn-success btn-sm"  %>
                <% elsif obj.type_of == "Other" %>
                  <%= link_to "Open", obj.content, target: "_blank", class: "btn btn-success btn-sm"  %>
                <% end %>

                </li>
                <!-- Single Resource Ends -->
                <% end %>
            <% end %>
          </ul>
          <% end %>
            <!--Resource container Ends -->

            <!-- Resources Controls Starts -->
            <div class="btn-group btn-group-lg" role="group">
              <div class="btn-group" role="group">
              <button class="control-icon fancy-button button-line no-text btn-col bell" id="feature-prev-shuffle" title="Previous" >
                <span class="glyphicon glyphicon-triangle-left" aria-hidden="true"></span>
              </button>
              </div>
              <div class="btn-group" role="group">
              <button class="control-icon fancy-button button-line no-text btn-col zoom" id="feature-expand-shuffle" title="Expand" >
                <span class="glyphicon glyphicon-resize-full" aria-hidden="true"></span>
              </button>
              </div>
              <div class="btn-group" role="group">
              <button class="control-icon fancy-button button-line no-text btn-col zoom" id="feature-close-shuffle" title="Collapse" >
                <span class="glyphicon glyphicon-resize-small" aria-hidden="true"></span>
              </button>
              </div>
              <div class="btn-group" role="group">
              <button class="control-icon fancy-button button-line no-text btn-col bell" id="feature-next-shuffle" title="Next" >
                <span class="glyphicon glyphicon-triangle-right" aria-hidden="true"></span>
              </button>
              </div>
            </div>
            <!-- Resources Controls Ends -->
        </div>
      </div>
    </div>
  </section>