config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  root 'categories#index'
  resources :categories do
    resources :tracks
  end

  resources :tracks do
    resources :lessons
  end

  resources :lessons do
    resources :resources
    resources :assessments
  end

  resources :assessments do
    resources :questions
  end

  resources :users do 
    resources :messages
  end
  resources :questions do 
    resources :answers
  end 

  resources :students_tracks

  get '/shuffle' => 'resources#shuffle', as: :shuffle

  get '/factoids' => 'factoids#show', as: :random_fact

  post 'resources/:id/complete' => 'resources#complete', as: :complete_element

end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id         :integer          not null, primary key
#  title      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Category < ActiveRecord::Base
  has_many :tracks
end

app/controllers/categories_controller.rb
# == Schema Information
#
# Table name: categories
#
#  id         :integer          not null, primary key
#  title      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class CategoriesController < ApplicationController
  include HTTParty


  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
    @tracks = @category.tracks

  end

end

app/helpers/categories_helper.rb
# == Schema Information
#
# Table name: categories
#
#  id         :integer          not null, primary key
#  title      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

module CategoriesHelper
end

app/views/categories/index.html.erb
<ul class="grid cs-style-3">
  <% @categories.each do |category| %>
  <li>
    <figure>
      <% if category.title == "Art" %>
        <%= image_tag "art", width: "242", height: "200"%>
      <% elsif category.title == "STEM"%>
        <%= image_tag "stem", width: "242", height: "200"%>
      <% elsif category.title == "Health"%>
        <%= image_tag "health", width: "242", height: "200"%>
      <% elsif category.title == "Language"%>
        <%= image_tag "language", width: "242", height: "200"%>
      <% elsif category.title == "Music"%>
        <%= image_tag "music", width: "242", height: "200"%>
      <% elsif category.title == "History"%>
        <%= image_tag "history", width: "242", height: "200"%>
      <% end %>
      <figcaption>
        <h3><%= category.title %></h3>
        <span></span>
        <p></p>
        <%= link_to "Start Learning", category_path(category)%>
      </figcaption>
    </figure>
  </li>
  <% end %>
</ul >

app/views/categories/show.html.erb
<h1> <%= @category.title %> </h1>
<ul>
<div class="row">
  <% @tracks.each do |track| %>
    <div class="col-sm-6 col-md-4">
      <div class="thumbnail">
        <img src=<%= track.image_url %>>
        <div class="caption">
          <h3><%= track.name %></h3>
          <p><%= track.description %></p>
          <p>
            <% if !current_user.student.nil? && current_user.student.tracks.include?(track) || current_user.teacher == track.teacher %>
              <a href="<%= track_path(track) %>" class="btn btn-primary" role="button">Open Track</a>
            <% else %>
              <a href="<%= track_path(track) %>" class="btn btn-primary" role="button">Preview Track</a>
              <%= link_to "Enroll", students_tracks_path(track_id: track.id), :method => :post, class: "btn btn-default", role: "button" %>
            <% end %>
          </p>
        </div>
      </div>
    </div>
  <% end %>
</div>

</ul>
<br><br>

<div class="create-new-track">
  <p><%= link_to "Create a New Track", new_category_track_path(@category.id) %></p>
  <br>
  <%= link_to(root_path) do %>
  <p><span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span>
    Return to Category Selection</p>
    <% end %>
</div>